#!/bin/bash

echo "================================================"
echo "🔧 INSTALANDO DEPENDÊNCIAS DO CHROME/SELENIUM"
echo "================================================"

# Detectar sistema operacional
if [ -f /etc/debian_version ]; then
    echo "✅ Sistema Debian/Ubuntu detectado"
    echo ""
    echo "Execute como root ou com sudo:"
    echo ""
    echo "sudo apt-get update"
    echo "sudo apt-get install -y \\"
    echo "    libnss3 \\"
    echo "    libnspr4 \\"
    echo "    libnssutil3 \\"
    echo "    libatk1.0-0 \\"
    echo "    libatk-bridge2.0-0 \\"
    echo "    libcups2 \\"
    echo "    libdrm2 \\"
    echo "    libdbus-1-3 \\"
    echo "    libatspi2.0-0 \\"
    echo "    libx11-6 \\"
    echo "    libxcomposite1 \\"
    echo "    libxdamage1 \\"
    echo "    libxext6 \\"
    echo "    libxfixes3 \\"
    echo "    libxrandr2 \\"
    echo "    libgbm1 \\"
    echo "    libxcb1 \\"
    echo "    libxkbcommon0 \\"
    echo "    libpango-1.0-0 \\"
    echo "    libcairo2 \\"
    echo "    libasound2"
    
elif [ -f /etc/redhat-release ]; then
    echo "✅ Sistema RedHat/CentOS detectado"
    echo ""
    echo "Execute como root ou com sudo:"
    echo ""
    echo "sudo yum install -y \\"
    echo "    nss \\"
    echo "    nspr \\"
    echo "    atk \\"
    echo "    at-spi2-atk \\"
    echo "    cups-libs \\"
    echo "    libdrm \\"
    echo "    libxkbcommon \\"
    echo "    libXcomposite \\"
    echo "    libXdamage \\"
    echo "    libXrandr \\"
    echo "    mesa-libgbm \\"
    echo "    pango \\"
    echo "    alsa-lib"
else
    echo "⚠️ Sistema não identificado"
    echo "Instale manualmente: libnss3, libnspr4, e outras dependências do Chrome"
fi

echo ""
echo "================================================"
echo "📝 APÓS INSTALAR AS DEPENDÊNCIAS:"
echo "================================================"
echo ""
echo "1. Teste o ChromeDriver:"
echo "   ~/.cache/selenium/chromedriver/linux64/*/chromedriver --version"
echo ""
echo "2. Configure o Chrome Debug:"
echo "   ./configurar_chrome_debug.sh"
echo ""
echo "3. Reinicie o servidor Flask"
echo ""
echo "================================================"