services:
  - type: web
    name: sistema-fretes
    env: python
    plan: starter
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: ./start_render.sh
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: WEB_CONCURRENCY
        value: 1
    autoDeploy: true
    
  # Configuração adicional de banco se necessário
  databases:
    - name: sistema-fretes-db
      plan: starter
