services:
  - type: web
    name: sistema-fretes
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python init_db.py && python create_admin.py && gunicorn run:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: FLASK_ENV
        value: "production"
      - key: DATABASE_URL
        fromDatabase:
          name: sistema-fretes-db
          property: connectionString

databases:
  - name: sistema-fretes-db
    databaseName: sistema_fretes
    user: sistema_user
    plan: free 