services:
  - type: web
    name: frete-sistema
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "python init_db.py && flask db upgrade && gunicorn --bind 0.0.0.0:$PORT --workers 2 --worker-class sync --timeout 600 --max-requests 1000 --max-requests-jitter 100 --keep-alive 10 --preload --worker-tmp-dir /dev/shm run:app"
    healthCheckPath: "/"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.4"
      - key: ENVIRONMENT
        value: "production"
      - key: FLASK_ENV
        value: "production"
      - key: PYTHONIOENCODING
        value: "utf-8"
      - key: LC_ALL
        value: "C.UTF-8"
      - key: LANG
        value: "C.UTF-8"
