services:
  - type: web
    name: frete-sistema
    env: python
    buildCommand: "./build.sh"
    startCommand: "./start_render.sh"
    plan: free
    region: oregon
    branch: main
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: frete-sistema-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WTF_CSRF_SECRET_KEY
        generateValue: true

databases:
  - name: frete-sistema-db
    databaseName: frete_sistema
    user: frete_user
    plan: free
    region: oregon
