services:
  - type: web
    name: frete-sistema
    env: python
    buildCommand: "./build.sh"
    startCommand: "python init_db.py && ./corrigir_migracao_render.sh && gunicorn --bind 0.0.0.0:$PORT --workers 2 --worker-class sync --timeout 600 --max-requests 1000 --max-requests-jitter 100 --keep-alive 10 --preload --worker-tmp-dir /dev/shm run:app"
    plan: free
    region: oregon
    branch: main
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: frete-sistema-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WTF_CSRF_SECRET_KEY
        generateValue: true

databases:
  - name: frete-sistema-db
    databaseName: frete_sistema
    user: frete_user
    plan: free
    region: oregon
