services:
  - type: web
    name: sistema-fretes
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python init_db.py && python fix_cnpj_columns.py && python create_admin.py && gunicorn --bind 0.0.0.0:$PORT --workers 1 --worker-class sync --timeout 600 --max-requests 500 --max-requests-jitter 50 --keep-alive 5 --preload run:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: FLASK_ENV
        value: "production"
      - key: DATABASE_URL
        fromDatabase:
          name: sistema-fretes-db
          property: connectionString

databases:
  - name: sistema-fretes-db
    databaseName: sistema_fretes
    user: sistema_user 