"""adicionar_campo_canhoto_entrega

Revision ID: e081b265991f
Revises: e468e43c3f66
Create Date: 2025-06-19 13:31:53.104202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e081b265991f'
down_revision = 'e468e43c3f66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entregas_monitoradas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('canhoto_arquivo', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entregas_monitoradas', schema=None) as batch_op:
        batch_op.drop_column('canhoto_arquivo')

    # ### end Alembic commands ###
