"""Remover constraint única da programação - permite múltiplas programações por produto/linha/data

Revision ID: e5ce86ab5c1d
Revises: 21038bb4724e
Create Date: 2025-07-01 12:56:11.681729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ce86ab5c1d'
down_revision = '21038bb4724e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programacao_producao', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uk_programacao_cliente_unica'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programacao_producao', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uk_programacao_cliente_unica'), ['data_programacao', 'linha_producao', 'cod_produto', 'cliente_produto'])

    # ### end Alembic commands ###
