BANCO = '310'
BANCO_NOME = 'VORTX DTVM'
RAZAO_SOCIAL = 'NACOM GOYA INDUSTRIA E COMERCI'
CONVENIO = '1095757'
AGENCIA = '0001'
CONTA_SEM_DV = '00109575'
CONTA_DV = '7'
CARTEIRA = '21'
SISTEMA_ID = 'MX'
ESPECIE_DUPLICATA = '01'
OCORRENCIA_REMESSA = '01'
ACEITE = 'N'

TIPO_COBRANCA_IDS = {
    1: 10,   # NACOM FB → BOLETO VORTX - FB
    4: 11,   # NACOM CD → BOLETO VORTX - CD
}

COMPANY_NAMES = {
    1: 'NACOM GOYA - FB',
    4: 'NACOM GOYA - CD',
}

CONTA_GRAFENO_HEADER = CONTA_SEM_DV[-7:].rjust(20, '0')

def id_empresa_detalhe():
    return '0' + CARTEIRA.zfill(3) + AGENCIA.zfill(5) + CONTA_SEM_DV[-7:] + CONTA_DV

LINE_WIDTH = 400
SEPARATOR = '\r\n'
