"""Remove server_default das colunas criado_por e criado_em

Revision ID: 02217b9a4021
Revises: ad20cb0cf2b0
Create Date: 2025-05-10 12:52:38.285936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02217b9a4021'
down_revision = 'ad20cb0cf2b0'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('tabelas_frete') as batch_op:
        batch_op.alter_column('criado_por', server_default=None)
        batch_op.alter_column('criado_em', server_default=None)


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabelas_frete', schema=None) as batch_op:
        batch_op.alter_column('criado_em',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###
