"""adicionar_campos_rota_subrota_carteira

Revision ID: 0ae5f539b83f
Revises: 7262b3209e6a
Create Date: 2025-07-18 00:17:13.146249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ae5f539b83f'
down_revision = '7262b3209e6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carteira_principal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rota', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sub_rota', sa.String(length=50), nullable=True))
        batch_op.drop_index(batch_op.f('idx_carteira_lote_separacao'))
        batch_op.drop_index(batch_op.f('ix_carteira_principal_lote_separacao_id'))
        batch_op.create_index('idx_carteira_separacao_lote', ['separacao_lote_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_carteira_principal_separacao_lote_id'), ['separacao_lote_id'], unique=False)
        batch_op.drop_column('lote_separacao_id')

    with op.batch_alter_table('controle_cruzado_separacao', schema=None) as batch_op:
        batch_op.alter_column('separacao_lote_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_controle_lote_pedido'))
        batch_op.drop_index(batch_op.f('ix_controle_cruzado_separacao_lote_separacao_id'))
        batch_op.create_index('idx_controle_separacao_lote_pedido', ['separacao_lote_id', 'num_pedido'], unique=False)
        batch_op.create_index(batch_op.f('ix_controle_cruzado_separacao_separacao_lote_id'), ['separacao_lote_id'], unique=False)
        batch_op.drop_column('lote_separacao_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('controle_cruzado_separacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lote_separacao_id', sa.INTEGER(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_controle_cruzado_separacao_separacao_lote_id'))
        batch_op.drop_index('idx_controle_separacao_lote_pedido')
        batch_op.create_index(batch_op.f('ix_controle_cruzado_separacao_lote_separacao_id'), ['lote_separacao_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_controle_lote_pedido'), ['lote_separacao_id', 'num_pedido'], unique=False)
        batch_op.alter_column('separacao_lote_id',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('carteira_principal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lote_separacao_id', sa.INTEGER(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_carteira_principal_separacao_lote_id'))
        batch_op.drop_index('idx_carteira_separacao_lote')
        batch_op.create_index(batch_op.f('ix_carteira_principal_lote_separacao_id'), ['lote_separacao_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_carteira_lote_separacao'), ['lote_separacao_id'], unique=False)
        batch_op.drop_column('sub_rota')
        batch_op.drop_column('rota')

    # ### end Alembic commands ###
