"""adicionado campos de auditoria no embarques

Revision ID: 0b82345ed7df
Revises: ac013018764a
Create Date: 2025-05-28 12:04:15.257497

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = '0b82345ed7df'
down_revision = 'ac013018764a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Adiciona as colunas como nullable primeiro
    with op.batch_alter_table('embarques', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criado_em', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('criado_por', sa.String(length=100), nullable=True))

    # Atualiza os registros existentes
    op.execute(f"UPDATE embarques SET criado_em = '{datetime.utcnow()}', criado_por = 'Administrador'")

    # Altera as colunas para not null
    with op.batch_alter_table('embarques', schema=None) as batch_op:
        batch_op.alter_column('criado_em', nullable=False)
        batch_op.alter_column('criado_por', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarques', schema=None) as batch_op:
        batch_op.drop_column('criado_por')
        batch_op.drop_column('criado_em')

    # ### end Alembic commands ###
