"""Adiciona coluna status na tabela pedidos

Revision ID: 115f23a90bbd
Revises: 5287492ae616
Create Date: 2025-05-24 13:31:34.721264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115f23a90bbd'
down_revision = '5287492ae616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.drop_index('idx_pedidos_cotacao_id')
        batch_op.drop_index('idx_pedidos_usuario_id')
        batch_op.create_foreign_key('fk_pedido_cotacao', 'cotacoes', ['cotacao_id'], ['id'])
        batch_op.create_foreign_key('fk_pedido_usuario', 'usuarios', ['usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pedido_usuario', type_='foreignkey')
        batch_op.drop_constraint('fk_pedido_cotacao', type_='foreignkey')
        batch_op.create_index('idx_pedidos_usuario_id', ['usuario_id'], unique=False)
        batch_op.create_index('idx_pedidos_cotacao_id', ['cotacao_id'], unique=False)
        batch_op.drop_column('status')

    # ### end Alembic commands ###
