"""Adicionar tabelas de aprendizado vitalicio Claude AI

Revision ID: 13d736405224
Revises: c3db1f628a77
Create Date: 2025-06-25 20:35:50.936330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13d736405224'
down_revision = 'c3db1f628a77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_learning_metrics',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('metrica_tipo', sa.VARCHAR(length=50), nullable=False),
    sa.Column('metrica_valor', sa.FLOAT(), nullable=False),
    sa.Column('contexto', sa.TEXT(), nullable=True),
    sa.Column('periodo_inicio', sa.TIMESTAMP(), nullable=False),
    sa.Column('periodo_fim', sa.TIMESTAMP(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_business_contexts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('contexto_nome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=True),
    sa.Column('regras', sa.TEXT(), nullable=False),
    sa.Column('exemplos', sa.TEXT(), nullable=True),
    sa.Column('restricoes', sa.TEXT(), nullable=True),
    sa.Column('prioridade', sa.INTEGER(), server_default=sa.text('50'), nullable=True),
    sa.Column('ativo', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_knowledge_patterns',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('pattern_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('pattern_text', sa.TEXT(), nullable=False),
    sa.Column('interpretation', sa.TEXT(), nullable=False),
    sa.Column('confidence', sa.FLOAT(), server_default=sa.text('0.5'), nullable=True),
    sa.Column('usage_count', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('success_rate', sa.FLOAT(), server_default=sa.text('0.5'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pattern_type', 'pattern_text')
    )
    op.create_table('ai_grupos_empresariais',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome_grupo', sa.VARCHAR(length=200), nullable=False),
    sa.Column('tipo_negocio', sa.VARCHAR(length=100), nullable=True),
    sa.Column('cnpj_prefixos', sa.TEXT(), nullable=True),
    sa.Column('palavras_chave', sa.TEXT(), nullable=True),
    sa.Column('filtro_sql', sa.TEXT(), nullable=False),
    sa.Column('regras_deteccao', sa.TEXT(), nullable=True),
    sa.Column('estatisticas', sa.TEXT(), nullable=True),
    sa.Column('ativo', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('aprendido_automaticamente', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('confirmado_por', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_response_templates',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tipo_consulta', sa.VARCHAR(length=100), nullable=False),
    sa.Column('contexto', sa.VARCHAR(length=100), nullable=True),
    sa.Column('template_resposta', sa.TEXT(), nullable=False),
    sa.Column('variaveis_necessarias', sa.TEXT(), nullable=True),
    sa.Column('exemplo_uso', sa.TEXT(), nullable=True),
    sa.Column('taxa_satisfacao', sa.FLOAT(), server_default=sa.text('0.5'), nullable=True),
    sa.Column('uso_count', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('ativo', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_semantic_mappings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('termo_usuario', sa.TEXT(), nullable=False),
    sa.Column('campo_sistema', sa.VARCHAR(length=100), nullable=False),
    sa.Column('modelo', sa.VARCHAR(length=50), nullable=False),
    sa.Column('contexto', sa.TEXT(), nullable=True),
    sa.Column('frequencia', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('ultima_uso', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('validado', sa.INTEGER(), server_default=sa.text('0'), nullable=True),
    sa.Column('validado_por', sa.VARCHAR(length=100), nullable=True),
    sa.Column('validado_em', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('termo_usuario', 'campo_sistema', 'modelo')
    )
    op.create_table('ai_learning_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('consulta_original', sa.TEXT(), nullable=False),
    sa.Column('interpretacao_inicial', sa.TEXT(), nullable=False),
    sa.Column('resposta_inicial', sa.TEXT(), nullable=True),
    sa.Column('feedback_usuario', sa.TEXT(), nullable=True),
    sa.Column('interpretacao_corrigida', sa.TEXT(), nullable=True),
    sa.Column('resposta_corrigida', sa.TEXT(), nullable=True),
    sa.Column('tipo_correcao', sa.VARCHAR(length=50), nullable=True),
    sa.Column('aprendizado_extraido', sa.TEXT(), nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), nullable=True),
    sa.Column('sessao_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_learning_history')
    op.drop_table('ai_semantic_mappings')
    op.drop_table('ai_response_templates')
    op.drop_table('ai_grupos_empresariais')
    op.drop_table('ai_knowledge_patterns')
    op.drop_table('ai_business_contexts')
    op.drop_table('ai_learning_metrics')
    # ### end Alembic commands ###
