"""adicionado valor, pelo e pallet total

Revision ID: 161a606acd6d
Revises: 0b82345ed7df
Create Date: 2025-05-28 12:24:07.093414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '161a606acd6d'
down_revision = '0b82345ed7df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarques', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pallet_total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('peso_total', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarques', schema=None) as batch_op:
        batch_op.drop_column('peso_total')
        batch_op.drop_column('pallet_total')
        batch_op.drop_column('valor_total')

    # ### end Alembic commands ###
