"""retirado optante do EI

Revision ID: 1796a9fd26ec
Revises: 98e9e00a9a5a
Create Date: 2025-05-28 15:38:37.718246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1796a9fd26ec'
down_revision = '98e9e00a9a5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarque_itens', schema=None) as batch_op:
        batch_op.drop_column('transportadora_optante')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarque_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transportadora_optante', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
