"""Add codigo_ibge to CidadeAtendida

Revision ID: 194161a06a7c
Revises: 47ff46e9b2a9
Create Date: 2025-05-05 01:25:28.307835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194161a06a7c'
down_revision = '47ff46e9b2a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cidades_atendidas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_ibge', sa.String(length=10), nullable=True))

    with op.batch_alter_table('relatorio_faturamento_importado', schema=None) as batch_op:
        batch_op.drop_index('ix_relatorio_faturamento_importado_numero_nf')
        batch_op.create_index(batch_op.f('ix_relatorio_faturamento_importado_numero_nf'), ['numero_nf'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatorio_faturamento_importado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relatorio_faturamento_importado_numero_nf'))
        batch_op.create_index('ix_relatorio_faturamento_importado_numero_nf', ['numero_nf'], unique=False)

    with op.batch_alter_table('cidades_atendidas', schema=None) as batch_op:
        batch_op.drop_column('codigo_ibge')

    # ### end Alembic commands ###
