"""adicionado tipo_cotacao no embarque

Revision ID: 196d16fa690e
Revises: 643e2ccc684c
Create Date: 2025-05-28 16:14:53.333179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '196d16fa690e'
down_revision = '643e2ccc684c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarques', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_cotacao', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarques', schema=None) as batch_op:
        batch_op.drop_column('tipo_cotacao')

    # ### end Alembic commands ###
