"""ajuste cidade_atendida

Revision ID: 2f2db28f83e2
Revises: 
Create Date: 2025-04-21 12:03:56.677225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f2db28f83e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabelas_frete', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uf_origem', sa.String(length=2), nullable=False))
        batch_op.add_column(sa.Column('uf_destino', sa.String(length=2), nullable=False))
        batch_op.add_column(sa.Column('nome_tabela', sa.String(length=50), nullable=False))
        # batch_op.drop_constraint(None, type_='foreignkey')  # ❌ Removido porque não tem nome
        batch_op.drop_column('cidade_id')
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabelas_frete', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cidade_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'cidades', ['cidade_id'], ['id'])
        batch_op.drop_column('nome_tabela')
        batch_op.drop_column('uf_destino')
        batch_op.drop_column('uf_origem')

    # ### end Alembic commands ###
