"""Adicionado parametros da tabela de frete na cotacao

Revision ID: 3367d9ddc17d
Revises: 196d16fa690e
Create Date: 2025-05-28 18:38:58.083144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3367d9ddc17d'
down_revision = '196d16fa690e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modalidade', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('nome_tabela', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('valor_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('percentual_valor', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('frete_minimo_valor', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('frete_minimo_peso', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('icms', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('percentual_gris', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pedagio_por_100kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('valor_tas', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('percentual_adv', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('percentual_rca', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('valor_despacho', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('valor_cte', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('icms_incluso', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotacoes', schema=None) as batch_op:
        batch_op.drop_column('icms_incluso')
        batch_op.drop_column('valor_cte')
        batch_op.drop_column('valor_despacho')
        batch_op.drop_column('percentual_rca')
        batch_op.drop_column('percentual_adv')
        batch_op.drop_column('valor_tas')
        batch_op.drop_column('pedagio_por_100kg')
        batch_op.drop_column('percentual_gris')
        batch_op.drop_column('icms')
        batch_op.drop_column('frete_minimo_peso')
        batch_op.drop_column('frete_minimo_valor')
        batch_op.drop_column('percentual_valor')
        batch_op.drop_column('valor_kg')
        batch_op.drop_column('nome_tabela')
        batch_op.drop_column('modalidade')

    # ### end Alembic commands ###
