"""add data_hora em registros de volta

Revision ID: 3a47ab8aa0ff
Revises: 773b8a927e8f
Create Date: 2025-05-06 09:01:09.176838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a47ab8aa0ff'
down_revision = '773b8a927e8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs_entrega', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_hora', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs_entrega', schema=None) as batch_op:
        batch_op.drop_column('data_hora')

    # ### end Alembic commands ###
