"""empty message

Revision ID: 47ff46e9b2a9
Revises: fe386beefdb7
Create Date: 2025-05-04 22:16:42.616857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47ff46e9b2a9'
down_revision = 'fe386beefdb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ocorrencias_entrega')
    with op.batch_alter_table('entregas_monitoradas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_nf', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('transportadora', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('municipio', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('vendedor', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('valor_nf', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('data_entrega_prevista', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('data_hora_entrega_realizada', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('entregue', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('motivo_reagendamento', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('observacao_operacional', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('pendencia_financeira', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('resposta_financeiro', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('criado_em', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('criado_por', sa.String(length=100), nullable=True))
        batch_op.alter_column('cliente',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_entregas_monitoradas_numero_nf'), ['numero_nf'], unique=False)
        batch_op.drop_column('data_agendamento')
        batch_op.drop_column('nota_fiscal')
        batch_op.drop_column('data_prevista')
        batch_op.drop_column('data_entrega')
        batch_op.drop_column('lead_time')
        batch_op.drop_column('status')
        batch_op.drop_column('cidade')
        batch_op.drop_column('protocolo_agendamento')

    with op.batch_alter_table('relatorio_faturamento_importado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendedor', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatorio_faturamento_importado', schema=None) as batch_op:
        batch_op.drop_column('vendedor')

    with op.batch_alter_table('entregas_monitoradas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protocolo_agendamento', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('cidade', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('lead_time', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('data_entrega', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('data_prevista', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('nota_fiscal', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('data_agendamento', sa.DATE(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_entregas_monitoradas_numero_nf'))
        batch_op.alter_column('cliente',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.drop_column('criado_por')
        batch_op.drop_column('criado_em')
        batch_op.drop_column('resposta_financeiro')
        batch_op.drop_column('pendencia_financeira')
        batch_op.drop_column('observacao_operacional')
        batch_op.drop_column('motivo_reagendamento')
        batch_op.drop_column('entregue')
        batch_op.drop_column('data_hora_entrega_realizada')
        batch_op.drop_column('data_entrega_prevista')
        batch_op.drop_column('valor_nf')
        batch_op.drop_column('vendedor')
        batch_op.drop_column('municipio')
        batch_op.drop_column('transportadora')
        batch_op.drop_column('numero_nf')

    op.create_table('ocorrencias_entrega',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('entrega_id', sa.INTEGER(), nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=100), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=True),
    sa.Column('custo', sa.FLOAT(), nullable=True),
    sa.Column('criado_em', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['entrega_id'], ['entregas_monitoradas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
