"""criacao de novo models

Revision ID: 48b79401078e
Revises: 73666697b877
Create Date: 2025-05-19 17:56:37.973236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48b79401078e'
down_revision = '73666697b877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('separacao_pedidos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('separacao_pedidos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('num_pedido', sa.VARCHAR(length=50), nullable=True),
    sa.Column('data_pedido', sa.DATE(), nullable=True),
    sa.Column('cnpj_cpf', sa.VARCHAR(length=20), nullable=True),
    sa.Column('raz_social_red', sa.VARCHAR(length=255), nullable=True),
    sa.Column('nome_cidade', sa.VARCHAR(length=100), nullable=True),
    sa.Column('cod_uf', sa.VARCHAR(length=2), nullable=False),
    sa.Column('cod_produto', sa.VARCHAR(length=50), nullable=True),
    sa.Column('nome_produto', sa.VARCHAR(length=255), nullable=True),
    sa.Column('qtd_saldo', sa.FLOAT(), nullable=True),
    sa.Column('valor_saldo', sa.FLOAT(), nullable=True),
    sa.Column('pallet', sa.FLOAT(), nullable=True),
    sa.Column('peso', sa.FLOAT(), nullable=True),
    sa.Column('rota', sa.VARCHAR(length=50), nullable=True),
    sa.Column('sub_rota', sa.VARCHAR(length=50), nullable=True),
    sa.Column('observ_ped_1', sa.VARCHAR(length=255), nullable=True),
    sa.Column('roteirizacao', sa.VARCHAR(length=255), nullable=True),
    sa.Column('expedicao', sa.DATE(), nullable=True),
    sa.Column('agendamento', sa.DATE(), nullable=True),
    sa.Column('protocolo', sa.VARCHAR(length=50), nullable=True),
    sa.Column('criado_em', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
