"""Add uf to CidadeAtendida

Revision ID: 4ef120f7f5b9
Revises: 194161a06a7c
Create Date: 2025-05-05 09:04:23.668509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ef120f7f5b9'
down_revision = '194161a06a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cidades_atendidas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uf', sa.String(length=2), nullable=False))
        batch_op.alter_column('codigo_ibge',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cidades_atendidas', schema=None) as batch_op:
        batch_op.alter_column('codigo_ibge',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.drop_column('uf')

    # ### end Alembic commands ###
