"""add autor e criado_em em eventos e custos

Revision ID: 50c4dff872a8
Revises: 5c541886579b
Create Date: 2025-05-06 08:45:36.923946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50c4dff872a8'
down_revision = '5c541886579b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('custos_extra_entrega', schema=None) as batch_op:
        batch_op.add_column(sa.Column('autor', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('criado_em', sa.DateTime(), nullable=True))

    with op.batch_alter_table('eventos_entrega', schema=None) as batch_op:
        batch_op.add_column(sa.Column('autor', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('criado_em', sa.DateTime(), nullable=True))

    with op.batch_alter_table('logs_entrega', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criado_em', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs_entrega', schema=None) as batch_op:
        batch_op.drop_column('criado_em')

    with op.batch_alter_table('eventos_entrega', schema=None) as batch_op:
        batch_op.drop_column('criado_em')
        batch_op.drop_column('autor')

    with op.batch_alter_table('custos_extra_entrega', schema=None) as batch_op:
        batch_op.drop_column('criado_em')
        batch_op.drop_column('autor')

    # ### end Alembic commands ###
