"""Alterado coluna volumes para permitir nulos

Revision ID: 514eb16401b4
Revises: fdd6f6f268bc
Create Date: 2025-05-29 15:44:27.479408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514eb16401b4'
down_revision = 'fdd6f6f268bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarque_itens', schema=None) as batch_op:
        batch_op.alter_column('volumes',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarque_itens', schema=None) as batch_op:
        batch_op.alter_column('volumes',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
