"""Adicionado campo icms_destino na tabela cotacoes

Revision ID: 52306d1fb12d
Revises: 514eb16401b4
Create Date: 2025-05-29 15:54:36.818605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52306d1fb12d'
down_revision = '514eb16401b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icms_destino', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotacoes', schema=None) as batch_op:
        batch_op.drop_column('icms_destino')

    # ### end Alembic commands ###
