"""Adiciona modelo de Cotação e relacionamentos

Revision ID: 5287492ae616
Revises: 57e47978861e
Create Date: 2025-05-23 15:08:09.197177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5287492ae616'
down_revision = '57e47978861e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cotacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('transportadora_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_fechamento', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transportadora_id'], ['transportadoras.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cotacao_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'cotacoes', ['cotacao_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cotacao_id')

    op.drop_table('cotacoes')
    # ### end Alembic commands ###
