"""adicionado data_agenda em EntregaMonitorada

Revision ID: 57a1dd2b92b0
Revises: bff9fdd3f877
Create Date: 2025-05-17 20:39:59.552157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57a1dd2b92b0'
down_revision = 'bff9fdd3f877'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entregas_monitoradas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_agenda', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entregas_monitoradas', schema=None) as batch_op:
        batch_op.drop_column('data_agenda')

    # ### end Alembic commands ###
