"""UniqueConstraint nos pedidos

Revision ID: 57e47978861e
Revises: 48b79401078e
Create Date: 2025-05-19 20:14:45.913073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e47978861e'
down_revision = '48b79401078e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_melhor_opcao', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lead_time', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uix_num_pedido_exped_agend_prot', ['num_pedido', 'expedicao', 'agendamento', 'protocolo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_constraint('uix_num_pedido_exped_agend_prot', type_='unique')
        batch_op.drop_column('lead_time')
        batch_op.drop_column('valor_melhor_opcao')

    # ### end Alembic commands ###
