"""corrigir_soft_delete_apenas_respostas

Revision ID: 5b695f58d103
Revises: 15d88e23b3e3
Create Date: 2025-06-16 20:55:57.074646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b695f58d103'
down_revision = '15d88e23b3e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendencias_financeiras_nf', schema=None) as batch_op:
        # Remove colunas antigas
        batch_op.drop_column('excluida_em')
        batch_op.drop_column('excluida_por')
        
        # Adiciona novas colunas para soft delete apenas das respostas
        batch_op.add_column(sa.Column('resposta_excluida_em', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('resposta_excluida_por', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendencias_financeiras_nf', schema=None) as batch_op:
        batch_op.drop_column('resposta_excluida_por')
        batch_op.drop_column('resposta_excluida_em')
        batch_op.add_column(sa.Column('excluida_por', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('excluida_em', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###
