"""add cnpj_cliente to entrega_monitorada

Revision ID: 5c541886579b
Revises: 4ef120f7f5b9
Create Date: 2025-05-05 20:56:27.068292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c541886579b'
down_revision = '4ef120f7f5b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entregas_monitoradas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnpj_cliente', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_entregas_monitoradas_cnpj_cliente'), ['cnpj_cliente'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entregas_monitoradas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entregas_monitoradas_cnpj_cliente'))
        batch_op.drop_column('cnpj_cliente')

    # ### end Alembic commands ###
