"""retirado tipo_carga do embarque

Revision ID: 643e2ccc684c
Revises: 1796a9fd26ec
Create Date: 2025-05-28 16:00:47.217597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '643e2ccc684c'
down_revision = '1796a9fd26ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarque_itens', schema=None) as batch_op:
        batch_op.drop_column('tipo_carga')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarque_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_carga', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
