"""Adicionar campo agendamento_confirmado na CarteiraPrincipal

Revision ID: 7262b3209e6a
Revises: b3959548cec6
Create Date: 2025-07-17 20:31:58.423944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7262b3209e6a'
down_revision = 'b3959548cec6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carteira_principal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agendamento_confirmado', sa.Boolean(), nullable=True, default=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carteira_principal', schema=None) as batch_op:
        batch_op.drop_column('agendamento_confirmado')
    # ### end Alembic commands ###
