"""Atualizar modelo de cidades

Revision ID: 7281ac6f126e
Revises: bb31adc4ed99
Create Date: 2025-05-11 18:41:36.019454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7281ac6f126e'
down_revision = 'bb31adc4ed99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cidades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('microrregiao', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('mesorregiao', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cidades', schema=None) as batch_op:
        batch_op.drop_column('mesorregiao')
        batch_op.drop_column('microrregiao')

    # ### end Alembic commands ###
