"""Alterado separacao tudo para nullable

Revision ID: 73666697b877
Revises: 88bac9754d09
Create Date: 2025-05-19 16:42:59.004404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73666697b877'
down_revision = '88bac9754d09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('separacao_pedidos', schema=None) as batch_op:
        batch_op.alter_column('num_pedido',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('cnpj_cpf',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('raz_social_red',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('nome_cidade',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('cod_produto',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('nome_produto',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('separacao_pedidos', schema=None) as batch_op:
        batch_op.alter_column('nome_produto',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('cod_produto',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('nome_cidade',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('raz_social_red',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('cnpj_cpf',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('num_pedido',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
