"""add finalizado to entrega_monitorada

Revision ID: 773b8a927e8f
Revises: 50c4dff872a8
Create Date: 2025-05-06 08:56:57.271861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '773b8a927e8f'
down_revision = '50c4dff872a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entregas_monitoradas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finalizado_por', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('finalizado_em', sa.DateTime(), nullable=True))

    with op.batch_alter_table('logs_entrega', schema=None) as batch_op:
        batch_op.drop_column('data_hora')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs_entrega', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_hora', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('entregas_monitoradas', schema=None) as batch_op:
        batch_op.drop_column('finalizado_em')
        batch_op.drop_column('finalizado_por')

    # ### end Alembic commands ###
