""" tirar o nullable tru

Revision ID: 88bac9754d09
Revises: 22fd94c4d36a
Create Date: 2025-05-19 13:17:47.236131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88bac9754d09'
down_revision = '22fd94c4d36a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('separacao_pedidos', schema=None) as batch_op:
        batch_op.alter_column('data_pedido',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('qtd_saldo',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('valor_saldo',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('pallet',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('peso',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('separacao_pedidos', schema=None) as batch_op:
        batch_op.alter_column('peso',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('pallet',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('valor_saldo',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('qtd_saldo',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('data_pedido',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
