"""retirado PedidoEmbarque

Revision ID: 92ecbd5aef7f
Revises: 7281ac6f126e
Create Date: 2025-05-12 17:43:41.446529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ecbd5aef7f'
down_revision = '7281ac6f126e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedidos_embarque')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos_embarque',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('embarque_id', sa.INTEGER(), nullable=False),
    sa.Column('cliente', sa.VARCHAR(length=120), nullable=False),
    sa.Column('uf_destino', sa.VARCHAR(length=2), nullable=False),
    sa.Column('cidade_destino', sa.VARCHAR(length=100), nullable=False),
    sa.Column('quantidade_volumes', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['embarque_id'], ['embarques.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
