"""Adiciona coluna nf_cd para status NF no CD

Revision ID: 94fb19af9c96
Revises: 494fa4ef6591
Create Date: 2025-06-09 17:43:04.858426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94fb19af9c96'
down_revision = '494fa4ef6591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fretes', schema=None) as batch_op:
        batch_op.drop_column('desconsiderar_diferenca')

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nf_cd', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('nf_cd')

    with op.batch_alter_table('fretes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desconsiderar_diferenca', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
