"""adicionado campos na cotacao

Revision ID: 98e9e00a9a5a
Revises: 161a606acd6d
Create Date: 2025-05-28 13:06:48.012745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98e9e00a9a5a'
down_revision = '161a606acd6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_carga', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('valor_total', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('peso_total', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotacoes', schema=None) as batch_op:
        batch_op.drop_column('peso_total')
        batch_op.drop_column('valor_total')
        batch_op.drop_column('tipo_carga')

    # ### end Alembic commands ###
