"""adicionado colunas no models embarques

Revision ID: a18bd519dc3b
Revises: ed52544c1dfe
Create Date: 2025-05-26 17:54:33.233754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a18bd519dc3b'
down_revision = 'ed52544c1dfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarque_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tabela_nome_tabela', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tabela_frete_minimo_valor', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_frete_minimo_peso', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_percentual_gris', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_pedagio_por_100kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_valor_tas', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_percentual_adv', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_percentual_rca', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_valor_despacho', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_valor_cte', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_icms_incluso', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('icms_destino', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('transportadora_optante', sa.Boolean(), nullable=True))
        batch_op.drop_column('tabela_pedagio')
        batch_op.drop_column('tabela_frete_valor')
        batch_op.drop_column('tabela_frete_minimo')
        batch_op.drop_column('tabela_nome')
        batch_op.drop_column('tabela_gris')
        batch_op.drop_column('tabela_tas')
        batch_op.drop_column('tabela_frete_peso')

    with op.batch_alter_table('embarques', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modalidade', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tabela_nome_tabela', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tabela_frete_minimo_valor', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_frete_minimo_peso', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_percentual_gris', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_pedagio_por_100kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_valor_tas', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_percentual_adv', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_percentual_rca', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_valor_despacho', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_valor_cte', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_icms_incluso', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('icms_destino', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('transportadora_optante', sa.Boolean(), nullable=True))
        batch_op.drop_column('tabela_pedagio')
        batch_op.drop_column('tabela_frete_valor')
        batch_op.drop_column('tabela_frete_minimo')
        batch_op.drop_column('tabela_nome')
        batch_op.drop_column('tabela_gris')
        batch_op.drop_column('tabela_tas')
        batch_op.drop_column('tabela_frete_peso')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarques', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tabela_frete_peso', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('tabela_tas', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('tabela_gris', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('tabela_nome', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('tabela_frete_minimo', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('tabela_frete_valor', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('tabela_pedagio', sa.FLOAT(), nullable=True))
        batch_op.drop_column('transportadora_optante')
        batch_op.drop_column('icms_destino')
        batch_op.drop_column('tabela_icms_incluso')
        batch_op.drop_column('tabela_valor_cte')
        batch_op.drop_column('tabela_valor_despacho')
        batch_op.drop_column('tabela_percentual_rca')
        batch_op.drop_column('tabela_percentual_adv')
        batch_op.drop_column('tabela_valor_tas')
        batch_op.drop_column('tabela_pedagio_por_100kg')
        batch_op.drop_column('tabela_percentual_gris')
        batch_op.drop_column('tabela_frete_minimo_peso')
        batch_op.drop_column('tabela_frete_minimo_valor')
        batch_op.drop_column('tabela_nome_tabela')
        batch_op.drop_column('modalidade')

    with op.batch_alter_table('embarque_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tabela_frete_peso', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('tabela_tas', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('tabela_gris', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('tabela_nome', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('tabela_frete_minimo', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('tabela_frete_valor', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('tabela_pedagio', sa.FLOAT(), nullable=True))
        batch_op.drop_column('transportadora_optante')
        batch_op.drop_column('icms_destino')
        batch_op.drop_column('tabela_icms_incluso')
        batch_op.drop_column('tabela_valor_cte')
        batch_op.drop_column('tabela_valor_despacho')
        batch_op.drop_column('tabela_percentual_rca')
        batch_op.drop_column('tabela_percentual_adv')
        batch_op.drop_column('tabela_valor_tas')
        batch_op.drop_column('tabela_pedagio_por_100kg')
        batch_op.drop_column('tabela_percentual_gris')
        batch_op.drop_column('tabela_frete_minimo_peso')
        batch_op.drop_column('tabela_frete_minimo_valor')
        batch_op.drop_column('tabela_nome_tabela')

    # ### end Alembic commands ###
