"""Adiciona campos resposta_logistica, respondida_em e respondida_por em PendenciaFinanceiraNF

Revision ID: a77c3fbf479e
Revises: 3a47ab8aa0ff
Create Date: 2025-05-08 20:42:39.258512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a77c3fbf479e'
down_revision = '3a47ab8aa0ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs_entrega', schema=None) as batch_op:
        batch_op.drop_column('criado_em')

    with op.batch_alter_table('pendencias_financeiras_nf', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resposta_logistica', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('respondida_em', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('respondida_por', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendencias_financeiras_nf', schema=None) as batch_op:
        batch_op.drop_column('respondida_por')
        batch_op.drop_column('respondida_em')
        batch_op.drop_column('resposta_logistica')

    with op.batch_alter_table('logs_entrega', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criado_em', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
