"""Adiciona campo observacao em AgendamentoEntrega

Revision ID: a7f466906586
Revises: 8c80fc53dd4d
Create Date: 2025-05-09 18:31:36.572100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7f466906586'
down_revision = '8c80fc53dd4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos_entrega', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacao', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamentos_entrega', schema=None) as batch_op:
        batch_op.drop_column('observacao')

    # ### end Alembic commands ###
