"""null true da data prev embarque

Revision ID: ac013018764a
Revises: e731018d12fd
Create Date: 2025-05-27 15:46:37.469792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac013018764a'
down_revision = 'e731018d12fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarques', schema=None) as batch_op:
        batch_op.alter_column('data_prevista_embarque',
               existing_type=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_DATE)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarques', schema=None) as batch_op:
        batch_op.alter_column('data_prevista_embarque',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_DATE)'))

    # ### end Alembic commands ###
