"""atualização das colunas da tabela

Revision ID: ad20cb0cf2b0
Revises: f4cc0851ffdc
Create Date: 2025-05-10 12:50:04.438160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad20cb0cf2b0'
down_revision = 'f4cc0851ffdc'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('tabelas_frete') as batch_op:
        batch_op.add_column(sa.Column('criado_por', sa.String(length=120), nullable=False, server_default='sistema'))
        batch_op.add_column(sa.Column('criado_em', sa.DateTime(), nullable=False, server_default=sa.func.now()))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabelas_frete', schema=None) as batch_op:
        batch_op.drop_column('criado_em')
        batch_op.drop_column('criado_por')

    # ### end Alembic commands ###
