"""adicionar_hora_agendamento_carteira

Revision ID: adicionar_hora_agendamento
Revises: e5ce86ab5c1d
Create Date: 2025-07-17 15:36:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adicionar_hora_agendamento'
down_revision = 'e5ce86ab5c1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carteira_principal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hora_agendamento', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carteira_principal', schema=None) as batch_op:
        batch_op.drop_column('hora_agendamento')
    # ### end Alembic commands ### 