"""tirar null=false do numero

Revision ID: aedb8491bea5
Revises: f0296813c691
Create Date: 2025-05-12 20:44:46.967721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aedb8491bea5'
down_revision = 'f0296813c691'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarques', schema=None) as batch_op:
        batch_op.alter_column('numero',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarques', schema=None) as batch_op:
        batch_op.alter_column('numero',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
