""" atualizacao forms e models embarques

Revision ID: af32c0ea0a6f
Revises: fd9d4972416a
Create Date: 2025-05-15 20:20:34.878102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af32c0ea0a6f'
down_revision = 'fd9d4972416a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarque_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_agenda', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarque_itens', schema=None) as batch_op:
        batch_op.drop_column('data_agenda')

    # ### end Alembic commands ###
