"""Criar tabela historico_tabelas_frete

Revision ID: bb31adc4ed99
Revises: 02217b9a4021
Create Date: 2025-05-10 17:05:29.877188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb31adc4ed99'
down_revision = '02217b9a4021'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabelas_frete', schema=None) as batch_op:
        batch_op.alter_column('criado_em',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabelas_frete', schema=None) as batch_op:
        batch_op.alter_column('criado_em',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
