"""Adiciona colunas cidade_normalizada e uf_normalizada

Revision ID: bc7d3c541c3b
Revises: update_status_default
Create Date: 2025-05-25 22:33:52.324937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc7d3c541c3b'
down_revision = 'update_status_default'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cidade_normalizada', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('uf_normalizada', sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('uf_normalizada')
        batch_op.drop_column('cidade_normalizada')

    # ### end Alembic commands ###
