"""adicionado nf_cd

Revision ID: bff9fdd3f877
Revises: af32c0ea0a6f
Create Date: 2025-05-16 19:28:04.740493

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bff9fdd3f877'
down_revision = 'af32c0ea0a6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entregas_monitoradas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nf_cd', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entregas_monitoradas', schema=None) as batch_op:
        batch_op.drop_column('nf_cd')

    # ### end Alembic commands ###
