"""adicionar_campo_freteiro_transportadoras

Revision ID: c3db1f628a77
Revises: e081b265991f
Create Date: 2025-06-19 14:22:52.447723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3db1f628a77'
down_revision = 'e081b265991f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transportadoras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('freteiro', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transportadoras', schema=None) as batch_op:
        batch_op.drop_column('freteiro')

    # ### end Alembic commands ###
