"""tirar null=false da transportadora

Revision ID: c759c527b4fc
Revises: aedb8491bea5
Create Date: 2025-05-12 20:45:46.466531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c759c527b4fc'
down_revision = 'aedb8491bea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarques', schema=None) as batch_op:
        batch_op.alter_column('transportadora_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarques', schema=None) as batch_op:
        batch_op.alter_column('transportadora_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
