"""Cria tabela de fretes lançados

Revision ID: c9c19ef29882
Revises: 2f2db28f83e2
Create Date: 2025-04-21 19:51:23.583150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c19ef29882'
down_revision = '2f2db28f83e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarques', schema=None) as batch_op:
        batch_op.add_column(sa.Column('placa_veiculo', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('tipo_coleta', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('paletizado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('laudo_anexado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('embalagem_aprovada', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('transporte_aprovado', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('horario_carregamento', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('responsavel_carregamento', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('nome_motorista', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cpf_motorista', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('qtd_pallets', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('data_embarque_str', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarques', schema=None) as batch_op:
        batch_op.drop_column('data_embarque_str')
        batch_op.drop_column('qtd_pallets')
        batch_op.drop_column('cpf_motorista')
        batch_op.drop_column('nome_motorista')
        batch_op.drop_column('responsavel_carregamento')
        batch_op.drop_column('horario_carregamento')
        batch_op.drop_column('transporte_aprovado')
        batch_op.drop_column('embalagem_aprovada')
        batch_op.drop_column('laudo_anexado')
        batch_op.drop_column('paletizado')
        batch_op.drop_column('tipo_coleta')
        batch_op.drop_column('placa_veiculo')

    # ### end Alembic commands ###
