"""Adicionar campos de cancelamento ao embarque

Revision ID: de0af0685921
Revises: 52306d1fb12d
Create Date: 2025-06-07 17:31:04.275201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de0af0685921'
down_revision = '52306d1fb12d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarque_itens', schema=None) as batch_op:
        batch_op.drop_index('idx_embarque_itens_lote_id')
        batch_op.create_index(batch_op.f('ix_embarque_itens_separacao_lote_id'), ['separacao_lote_id'], unique=False)

    with op.batch_alter_table('embarques', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo_cancelamento', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cancelado_em', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancelado_por', sa.String(length=100), nullable=True))

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_index('idx_pedidos_lote_id')
        batch_op.create_index(batch_op.f('ix_pedidos_separacao_lote_id'), ['separacao_lote_id'], unique=False)

    with op.batch_alter_table('separacao', schema=None) as batch_op:
        batch_op.drop_index('idx_separacao_lote_id')
        batch_op.create_index(batch_op.f('ix_separacao_separacao_lote_id'), ['separacao_lote_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('separacao', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_separacao_separacao_lote_id'))
        batch_op.create_index('idx_separacao_lote_id', ['separacao_lote_id'], unique=False)

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedidos_separacao_lote_id'))
        batch_op.create_index('idx_pedidos_lote_id', ['separacao_lote_id'], unique=False)

    with op.batch_alter_table('embarques', schema=None) as batch_op:
        batch_op.drop_column('cancelado_por')
        batch_op.drop_column('cancelado_em')
        batch_op.drop_column('motivo_cancelamento')

    with op.batch_alter_table('embarque_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_embarque_itens_separacao_lote_id'))
        batch_op.create_index('idx_embarque_itens_lote_id', ['separacao_lote_id'], unique=False)

    # ### end Alembic commands ###
