"""adicionado lead time em EntregaMonitorada

Revision ID: e2749849661b
Revises: 57a1dd2b92b0
Create Date: 2025-05-17 22:50:42.090781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2749849661b'
down_revision = '57a1dd2b92b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entregas_monitoradas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lead_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entregas_monitoradas', schema=None) as batch_op:
        batch_op.drop_column('lead_time')

    # ### end Alembic commands ###
