"""add modalidade

Revision ID: e731018d12fd
Revises: e9ab7ed5cce3
Create Date: 2025-05-27 15:45:28.167593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e731018d12fd'
down_revision = 'e9ab7ed5cce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_embarque_itens')
    with op.batch_alter_table('embarque_itens', schema=None) as batch_op:
        batch_op.alter_column('nota_fiscal',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    with op.batch_alter_table('embarques', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modalidade', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tabela_nome_tabela', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tabela_frete_minimo_valor', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_frete_minimo_peso', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_percentual_gris', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_pedagio_por_100kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_valor_tas', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_percentual_adv', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_percentual_rca', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_valor_despacho', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_valor_cte', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_icms_incluso', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('icms_destino', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('transportadora_optante', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarques', schema=None) as batch_op:
        batch_op.drop_column('transportadora_optante')
        batch_op.drop_column('icms_destino')
        batch_op.drop_column('tabela_icms_incluso')
        batch_op.drop_column('tabela_valor_cte')
        batch_op.drop_column('tabela_valor_despacho')
        batch_op.drop_column('tabela_percentual_rca')
        batch_op.drop_column('tabela_percentual_adv')
        batch_op.drop_column('tabela_valor_tas')
        batch_op.drop_column('tabela_pedagio_por_100kg')
        batch_op.drop_column('tabela_percentual_gris')
        batch_op.drop_column('tabela_frete_minimo_peso')
        batch_op.drop_column('tabela_frete_minimo_valor')
        batch_op.drop_column('tabela_nome_tabela')
        batch_op.drop_column('modalidade')

    with op.batch_alter_table('embarque_itens', schema=None) as batch_op:
        batch_op.alter_column('nota_fiscal',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    op.create_table('_alembic_tmp_embarque_itens',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tabela_nome_tabela', sa.VARCHAR(length=100), nullable=True),
    sa.Column('tabela_frete_minimo_valor', sa.FLOAT(), nullable=True),
    sa.Column('tabela_frete_minimo_peso', sa.FLOAT(), nullable=True),
    sa.Column('tabela_percentual_gris', sa.FLOAT(), nullable=True),
    sa.Column('tabela_pedagio_por_100kg', sa.FLOAT(), nullable=True),
    sa.Column('tabela_valor_tas', sa.FLOAT(), nullable=True),
    sa.Column('tabela_percentual_adv', sa.FLOAT(), nullable=True),
    sa.Column('tabela_percentual_rca', sa.FLOAT(), nullable=True),
    sa.Column('tabela_valor_despacho', sa.FLOAT(), nullable=True),
    sa.Column('tabela_valor_cte', sa.FLOAT(), nullable=True),
    sa.Column('tabela_icms_incluso', sa.BOOLEAN(), nullable=True),
    sa.Column('icms_destino', sa.FLOAT(), nullable=True),
    sa.Column('transportadora_optante', sa.BOOLEAN(), nullable=True),
    sa.Column('embarque_id', sa.INTEGER(), nullable=False),
    sa.Column('cliente', sa.VARCHAR(length=120), nullable=False),
    sa.Column('pedido', sa.VARCHAR(length=50), nullable=False),
    sa.Column('protocolo_agendamento', sa.VARCHAR(length=50), nullable=True),
    sa.Column('nota_fiscal', sa.VARCHAR(length=20), nullable=True),
    sa.Column('volumes', sa.INTEGER(), nullable=False),
    sa.Column('uf_destino', sa.VARCHAR(length=2), nullable=False),
    sa.Column('cidade_destino', sa.VARCHAR(length=100), nullable=False),
    sa.Column('data_agenda', sa.VARCHAR(length=10), nullable=True),
    sa.Column('peso', sa.FLOAT(), nullable=True),
    sa.Column('valor', sa.FLOAT(), nullable=True),
    sa.Column('cotacao_id', sa.INTEGER(), nullable=True),
    sa.Column('tipo_carga', sa.VARCHAR(length=20), nullable=True),
    sa.Column('modalidade', sa.VARCHAR(length=50), nullable=True),
    sa.Column('tabela_valor_kg', sa.FLOAT(), nullable=True),
    sa.Column('tabela_percentual_valor', sa.FLOAT(), nullable=True),
    sa.Column('tabela_icms', sa.FLOAT(), nullable=True),
    sa.Column('cnpj_cliente', sa.VARCHAR(length=30), nullable=False),
    sa.ForeignKeyConstraint(['cotacao_id'], ['cotacoes.id'], name='fk_embarque_item_cotacao'),
    sa.ForeignKeyConstraint(['embarque_id'], ['embarques.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
