"""adicionado data_prevista_embarque

Revision ID: e9ab7ed5cce3
Revises: a18bd519dc3b
Create Date: 2025-05-27 15:36:35.532558

"""
from alembic import op
import sqlalchemy as sa
from datetime import date


# revision identifiers, used by Alembic.
revision = 'e9ab7ed5cce3'
down_revision = 'a18bd519dc3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Cria uma nova tabela com a coluna adicional
    op.execute("""
        CREATE TABLE embarques_new (
            id INTEGER NOT NULL,
            numero INTEGER,
            transportadora_id INTEGER,
            observacoes TEXT,
            placa_veiculo VARCHAR(10),
            paletizado BOOLEAN,
            laudo_anexado BOOLEAN,
            embalagem_aprovada BOOLEAN,
            transporte_aprovado BOOLEAN,
            horario_carregamento VARCHAR(5),
            responsavel_carregamento VARCHAR(100),
            nome_motorista VARCHAR(100),
            cpf_motorista VARCHAR(20),
            qtd_pallets INTEGER,
            data_embarque_str VARCHAR(10),
            data_embarque DATE,
            status VARCHAR(20),
            cotacao_id INTEGER,
            tipo_carga VARCHAR(20),
            tabela_valor_kg FLOAT,
            tabela_percentual_valor FLOAT,
            tabela_icms FLOAT,
            data_prevista_embarque DATE NOT NULL DEFAULT CURRENT_DATE,
            PRIMARY KEY (id),
            FOREIGN KEY(transportadora_id) REFERENCES transportadoras (id),
            FOREIGN KEY(cotacao_id) REFERENCES cotacoes (id),
            UNIQUE (numero)
        )
    """)

    # Copia os dados da tabela antiga para a nova
    op.execute("""
        INSERT INTO embarques_new (
            id, numero, transportadora_id, observacoes, placa_veiculo, paletizado,
            laudo_anexado, embalagem_aprovada, transporte_aprovado, horario_carregamento,
            responsavel_carregamento, nome_motorista, cpf_motorista, qtd_pallets,
            data_embarque_str, data_embarque, status, cotacao_id, tipo_carga,
            tabela_valor_kg, tabela_percentual_valor, tabela_icms, data_prevista_embarque
        )
        SELECT
            id, numero, transportadora_id, observacoes, placa_veiculo, paletizado,
            laudo_anexado, embalagem_aprovada, transporte_aprovado, horario_carregamento,
            responsavel_carregamento, nome_motorista, cpf_motorista, qtd_pallets,
            data_embarque_str, data_embarque, status, cotacao_id, tipo_carga,
            tabela_valor_kg, tabela_percentual_valor, tabela_icms, CURRENT_DATE
        FROM embarques
    """)

    # Remove a tabela antiga
    op.execute("DROP TABLE embarques")

    # Renomeia a nova tabela
    op.execute("ALTER TABLE embarques_new RENAME TO embarques")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Cria uma nova tabela sem a coluna data_prevista_embarque
    op.execute("""
        CREATE TABLE embarques_new (
            id INTEGER NOT NULL,
            numero INTEGER,
            transportadora_id INTEGER,
            observacoes TEXT,
            placa_veiculo VARCHAR(10),
            paletizado BOOLEAN,
            laudo_anexado BOOLEAN,
            embalagem_aprovada BOOLEAN,
            transporte_aprovado BOOLEAN,
            horario_carregamento VARCHAR(5),
            responsavel_carregamento VARCHAR(100),
            nome_motorista VARCHAR(100),
            cpf_motorista VARCHAR(20),
            qtd_pallets INTEGER,
            data_embarque_str VARCHAR(10),
            data_embarque DATE,
            status VARCHAR(20),
            cotacao_id INTEGER,
            tipo_carga VARCHAR(20),
            tabela_valor_kg FLOAT,
            tabela_percentual_valor FLOAT,
            tabela_icms FLOAT,
            PRIMARY KEY (id),
            FOREIGN KEY(transportadora_id) REFERENCES transportadoras (id),
            FOREIGN KEY(cotacao_id) REFERENCES cotacoes (id),
            UNIQUE (numero)
        )
    """)

    # Copia os dados da tabela antiga para a nova
    op.execute("""
        INSERT INTO embarques_new (
            id, numero, transportadora_id, observacoes, placa_veiculo, paletizado,
            laudo_anexado, embalagem_aprovada, transporte_aprovado, horario_carregamento,
            responsavel_carregamento, nome_motorista, cpf_motorista, qtd_pallets,
            data_embarque_str, data_embarque, status, cotacao_id, tipo_carga,
            tabela_valor_kg, tabela_percentual_valor, tabela_icms
        )
        SELECT
            id, numero, transportadora_id, observacoes, placa_veiculo, paletizado,
            laudo_anexado, embalagem_aprovada, transporte_aprovado, horario_carregamento,
            responsavel_carregamento, nome_motorista, cpf_motorista, qtd_pallets,
            data_embarque_str, data_embarque, status, cotacao_id, tipo_carga,
            tabela_valor_kg, tabela_percentual_valor, tabela_icms
        FROM embarques
    """)

    # Remove a tabela antiga
    op.execute("DROP TABLE embarques")

    # Renomeia a nova tabela
    op.execute("ALTER TABLE embarques_new RENAME TO embarques")

    # ### end Alembic commands ###
