"""alteração do models embarque

Revision ID: ed52544c1dfe
Revises: bc7d3c541c3b
Create Date: 2025-05-26 15:57:51.989680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed52544c1dfe'
down_revision = 'bc7d3c541c3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarque_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peso', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('valor', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cotacao_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tipo_carga', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('modalidade', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tabela_nome', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tabela_valor_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_percentual_valor', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_frete_minimo', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_frete_peso', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_frete_valor', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_icms', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_gris', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_pedagio', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_tas', sa.Float(), nullable=True))
        batch_op.create_foreign_key('fk_embarque_item_cotacao', 'cotacoes', ['cotacao_id'], ['id'])

    with op.batch_alter_table('embarques', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cotacao_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tipo_carga', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tabela_nome', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tabela_valor_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_percentual_valor', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_frete_minimo', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_frete_peso', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_frete_valor', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_icms', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_gris', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_pedagio', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tabela_tas', sa.Float(), nullable=True))
        batch_op.create_foreign_key('fk_embarque_cotacao', 'cotacoes', ['cotacao_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarques', schema=None) as batch_op:
        batch_op.drop_constraint('fk_embarque_cotacao', type_='foreignkey')
        batch_op.drop_column('tabela_tas')
        batch_op.drop_column('tabela_pedagio')
        batch_op.drop_column('tabela_gris')
        batch_op.drop_column('tabela_icms')
        batch_op.drop_column('tabela_frete_valor')
        batch_op.drop_column('tabela_frete_peso')
        batch_op.drop_column('tabela_frete_minimo')
        batch_op.drop_column('tabela_percentual_valor')
        batch_op.drop_column('tabela_valor_kg')
        batch_op.drop_column('tabela_nome')
        batch_op.drop_column('tipo_carga')
        batch_op.drop_column('cotacao_id')

    with op.batch_alter_table('embarque_itens', schema=None) as batch_op:
        batch_op.drop_constraint('fk_embarque_item_cotacao', type_='foreignkey')
        batch_op.drop_column('tabela_tas')
        batch_op.drop_column('tabela_pedagio')
        batch_op.drop_column('tabela_gris')
        batch_op.drop_column('tabela_icms')
        batch_op.drop_column('tabela_frete_valor')
        batch_op.drop_column('tabela_frete_peso')
        batch_op.drop_column('tabela_frete_minimo')
        batch_op.drop_column('tabela_percentual_valor')
        batch_op.drop_column('tabela_valor_kg')
        batch_op.drop_column('tabela_nome')
        batch_op.drop_column('modalidade')
        batch_op.drop_column('tipo_carga')
        batch_op.drop_column('cotacao_id')
        batch_op.drop_column('valor')
        batch_op.drop_column('peso')

    # ### end Alembic commands ###
