"""adicionado status em Embarque

Revision ID: f0296813c691
Revises: 92ecbd5aef7f
Create Date: 2025-05-12 20:29:41.855264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0296813c691'
down_revision = '92ecbd5aef7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarques', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarques', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
