"""Adiciona coluna data_embarque em EntregaMonitorada

Revision ID: f4cc0851ffdc
Revises: a7f466906586
Create Date: 2025-05-10 11:47:28.935230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4cc0851ffdc'
down_revision = 'a7f466906586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabelas_frete', schema=None) as batch_op:
        batch_op.add_column(sa.Column('percentual_gris', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('percentual_adv', sa.Float(), nullable=True))
        batch_op.drop_column('percentual_gris_adv')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabelas_frete', schema=None) as batch_op:
        batch_op.add_column(sa.Column('percentual_gris_adv', sa.FLOAT(), nullable=True))
        batch_op.drop_column('percentual_adv')
        batch_op.drop_column('percentual_gris')

    # ### end Alembic commands ###
