"""Status finalizacao e troca de NF

Revision ID: fd9d4972416a
Revises: c759c527b4fc
Create Date: 2025-05-14 18:25:58.114291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd9d4972416a'
down_revision = 'c759c527b4fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('entregas_monitoradas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_finalizacao', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('nova_nf', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('substituida_por_nf_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_substituida_por_nf_id', 'entregas_monitoradas', ['substituida_por_nf_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entregas_monitoradas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('substituida_por_nf_id')
        batch_op.drop_column('nova_nf')
        batch_op.drop_column('status_finalizacao')

    with op.batch_alter_table('comentarios_nf', schema=None) as batch_op:
        batch_op.drop_column('arquivo')

    # ### end Alembic commands ###
