"""Adicionado modelo CotacaoItem e seus campos

Revision ID: fdd6f6f268bc
Revises: 3367d9ddc17d
Create Date: 2025-05-29 12:12:10.174649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdd6f6f268bc'
down_revision = '3367d9ddc17d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotacao_itens', schema=None) as batch_op:
        batch_op.alter_column('cnpj_cliente',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=14),
               nullable=False)
        batch_op.alter_column('cliente',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('modalidade',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cotacao_itens', schema=None) as batch_op:
        batch_op.alter_column('modalidade',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('cliente',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('cnpj_cliente',
               existing_type=sa.String(length=14),
               type_=sa.VARCHAR(length=30),
               nullable=True)

    # ### end Alembic commands ###
