"""Cria tabela relatorio_faturamento_importado

Revision ID: fe386beefdb7
Revises: c9c19ef29882
Create Date: 2025-05-03 19:18:13.702410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe386beefdb7'
down_revision = 'c9c19ef29882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarques', schema=None) as batch_op:
        batch_op.alter_column('id',
            existing_type=sa.INTEGER(),
            nullable=False,
            autoincrement=True)
        batch_op.create_unique_constraint("uq_embarques_numero", ['numero'])
        batch_op.create_foreign_key("fk_embarques_transportadora", 'transportadoras', ['transportadora_id'], ['id'])
        batch_op.drop_column('tipo_coleta')

        # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarques', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_coleta', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_constraint("fk_embarques_transportadora", type_='foreignkey')
        batch_op.drop_constraint("uq_embarques_numero", type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
