"""Adicionar campo pallets ao EmbarqueItem

Revision ID: 966e200086d8
Revises: 5c05ac0ba999
Create Date: 2025-06-13 16:30:18.614234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '966e200086d8'
down_revision = '5c05ac0ba999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarque_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pallets', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('embarque_itens', schema=None) as batch_op:
        batch_op.drop_column('pallets')

    # ### end Alembic commands ###
