"""Adicionar campos de auditoria na portaria com valores padrao

Revision ID: 97ff869fee50
Revises: 
Create Date: 2025-06-12 13:02:16.432894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97ff869fee50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ✅ CORRIGE CAMPOS DE AUDITORIA: Busca ou cria usuário padrão
    connection = op.get_bind()
    
    # Verifica se existe usuário "Rafael de Carvalho Nascimento"
    result = connection.execute(sa.text("SELECT id FROM usuarios WHERE nome = 'Rafael de Carvalho Nascimento' LIMIT 1"))
    usuario_padrao = result.fetchone()
    
    if usuario_padrao:
        usuario_id = usuario_padrao[0]
        print(f"✅ Usuário encontrado: Rafael de Carvalho Nascimento (ID: {usuario_id})")
    else:
        # Cria usuário padrão se não existir
        connection.execute(sa.text("""
            INSERT INTO usuarios (nome, email, senha_hash, perfil, status, criado_em) 
            VALUES ('Rafael de Carvalho Nascimento', 'rafael.admin@sistema.com', 'pbkdf2:sha256:600000$temp$temp', 'administrador', 'ativo', datetime('now'))
        """))
        result = connection.execute(sa.text("SELECT id FROM usuarios WHERE nome = 'Rafael de Carvalho Nascimento' LIMIT 1"))
        usuario_id = result.fetchone()[0]
        print(f"✅ Usuário criado: Rafael de Carvalho Nascimento (ID: {usuario_id})")
    
    with op.batch_alter_table('controle_portaria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registrado_por_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('atualizado_por_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_controle_portaria_atualizado_por', 'usuarios', ['atualizado_por_id'], ['id'])
        batch_op.create_foreign_key('fk_controle_portaria_registrado_por', 'usuarios', ['registrado_por_id'], ['id'])
    
    # ✅ ATUALIZA REGISTROS EXISTENTES com usuário padrão
    connection.execute(sa.text(f"""
        UPDATE controle_portaria 
        SET registrado_por_id = {usuario_id}, atualizado_por_id = {usuario_id}
        WHERE registrado_por_id IS NULL OR atualizado_por_id IS NULL
    """))
    print(f"✅ Registros existentes da portaria atualizados com usuário padrão")

    with op.batch_alter_table('cotacao_itens', schema=None) as batch_op:
        batch_op.alter_column('cnpj_cliente',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.String(length=20),
               existing_nullable=False)

    with op.batch_alter_table('embarque_itens', schema=None) as batch_op:
        batch_op.alter_column('cnpj_cliente',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               existing_nullable=True)

    with op.batch_alter_table('transportadoras', schema=None) as batch_op:
        batch_op.alter_column('cnpj',
               existing_type=sa.VARCHAR(length=18),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transportadoras', schema=None) as batch_op:
        batch_op.alter_column('cnpj',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=18),
               existing_nullable=False)

    with op.batch_alter_table('embarque_itens', schema=None) as batch_op:
        batch_op.alter_column('cnpj_cliente',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)

    with op.batch_alter_table('cotacao_itens', schema=None) as batch_op:
        batch_op.alter_column('cnpj_cliente',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=14),
               existing_nullable=False)

    with op.batch_alter_table('controle_portaria', schema=None) as batch_op:
        batch_op.drop_constraint('fk_controle_portaria_atualizado_por', type_='foreignkey')
        batch_op.drop_constraint('fk_controle_portaria_registrado_por', type_='foreignkey')
        batch_op.drop_column('atualizado_por_id')
        batch_op.drop_column('registrado_por_id')

    # ### end Alembic commands ###
