# Prometheus configuration for MCP Frete Sistema

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'mcp-frete-sistema'
    environment: 'production'

# Alert rules
rule_files:
  - /etc/prometheus/rules/*.yml

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# Scrape configurations
scrape_configs:
  # MCP Application metrics
  - job_name: 'mcp-app'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'mcp-frete-sistema'
          component: 'application'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
  
  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
        labels:
          service: 'mcp-frete-sistema'
          component: 'system'
  
  # PostgreSQL exporter
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['localhost:9187']
        labels:
          service: 'mcp-frete-sistema'
          component: 'database'
  
  # Redis exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['localhost:9121']
        labels:
          service: 'mcp-frete-sistema'
          component: 'cache'
  
  # Dashboard metrics
  - job_name: 'mcp-dashboard'
    static_configs:
      - targets: ['localhost:5001']
        labels:
          service: 'mcp-frete-sistema'
          component: 'monitoring'
    metrics_path: '/metrics'
  
  # Additional services (if needed)
  - job_name: 'nginx'
    static_configs:
      - targets: ['localhost:9113']
        labels:
          service: 'mcp-frete-sistema'
          component: 'proxy'

# Remote write configuration (optional)
# remote_write:
#   - url: http://remote-prometheus:9090/api/v1/write
#     remote_timeout: 30s
#     queue_config:
#       capacity: 10000
#       max_shards: 200
#       min_shards: 1
#       max_samples_per_send: 1000
#       batch_send_deadline: 5s
#       min_backoff: 30ms
#       max_backoff: 100ms

# Remote read configuration (optional)
# remote_read:
#   - url: http://remote-prometheus:9090/api/v1/read
#     remote_timeout: 1m
#     read_recent: true