"""adicionar_soft_delete_pendencias

Revision ID: 15d88e23b3e3
Revises: 03a18570776f
Create Date: 2025-06-16 20:47:45.059717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15d88e23b3e3'
down_revision = '03a18570776f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendencias_financeiras_nf', schema=None) as batch_op:
        batch_op.add_column(sa.Column('excluida_em', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('excluida_por', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pendencias_financeiras_nf', schema=None) as batch_op:
        batch_op.drop_column('excluida_por')
        batch_op.drop_column('excluida_em')
    # ### end Alembic commands ###
