"""Alterar constraint programacao: incluir cliente na chave unica

Revision ID: 21038bb4724e
Revises: 32a9fa957ff1
Create Date: 2025-07-01 12:11:57.146783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21038bb4724e'
down_revision = '32a9fa957ff1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programacao_producao', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uk_programacao_unica'), type_='unique')
        batch_op.create_unique_constraint('uk_programacao_cliente_unica', ['data_programacao', 'linha_producao', 'cod_produto', 'cliente_produto'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programacao_producao', schema=None) as batch_op:
        batch_op.drop_constraint('uk_programacao_cliente_unica', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uk_programacao_unica'), ['data_programacao', 'linha_producao', 'cod_produto'])

    # ### end Alembic commands ###
